version: '3.8'

services:
  authservice:
    build: .
    container_name: authservice
    ports:
      - 8001:8000
    volumes:
      - ./keys:/app/keys
    env_file:
      - .env
    networks:
      - mongodb-network
    restart: unless-stopped

networks:
  mongodb-network:
    external: true
